apiVersion: v1
kind: Service
metadata:
  name: decisionservice
spec:
  selector:
    app: decisionpod
  # type: NodePort # For NodePort Service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # App will be accessable on the port 80 of External IP
      targetPort: 5000
      # nodePort: 30001 # App will be accessable from http://Master_Node_IP:300001 for NodePort Service
