apiVersion: app/v1
kind: Deployment
metadata:
  name: decisiondeploy
  labels:
    app: decisiondeploy
spec:
  selector:
    matchlabels:
      app: decisiondeploy
  replicas: 2
  template: #Pod definition
    metadata:
      labels:
        app: decisionpod
    spec:
      containers:
        - name: decisioncon
          image: eshghi26/decisionfinal:latest
          ports:
            - name: decision-port
              containerport: 5000
          volumeMounts:
            - name: local-storage
            mountPath: /app
      nodeSelector:
        role: worker
      volumes:
        - name: local-storage
          persistentVolumeClaim:
          claimName: my-local-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/vagrant/decisionfile
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - worker01
            - worker02

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
