apiVersion: v1
kind: Service
metadata:
  name: decisionservice
spec:
  selector:
    app: decisionpod
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001 # App will be accessable from http://Master_Node_IP:300001
